### ISSUE TITLE
Net::SSH::ConnectionTimeout

### ISSUE THREAD

**Issue by mudasirraza** [envato/ami-spec#50]
Recently I was getting **Net::SSH::ConnectionTimeout** error, and then I found out that this exception is not rescued [here](https://github.com/envato/ami-spec/blob/13a94bac5e1133d7b4e378c3d0d4c88b9e076b10/lib/ami_spec/wait_for_ssh.rb#L12). So the script will end in first try irrespective of **ssh_retries** value. I was hoping it for to be rescued by Timeout::Error. Any idea why this exception is not included, as it is a common timeout error for Net::SSH? I can submit a PR if required. thanks

**Comment by patrobinson** [comment]
That exception is inherited from `Net::SSH::Exception`. I think we should just rescue `Net::SSH::Exception` which will catch this and any others.

**Comment by patrobinson** [comment]
Fixed in #57
